---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update package cache and install common packages
  apt:
    name: [curl, wget, git, vim, python3, python3-pip, acl]
    update_cache: yes
    state: present
  when: ansible_os_family == "Debian"
