---
- name: Install dependencies for App4
  apt:
    name: [ruby, ruby-dev, build-essential, gnupg, curl]
    state: present
    update_cache: yes

- name: Add MongoDB GPG key
  apt_key:
    url: https://pgp.mongodb.com/server-6.0.asc
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse
    state: present

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes

- name: Install Bundler
  apt:
    name: ruby-bundler
    state: present

- name: Create app directory
  file:
    path: /home/vagrant/app
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Copy App4 code
  copy:
    src: app4/
    dest: /home/vagrant/app/
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Install App Dependencies
  command: bundle install
  args:
    chdir: /home/vagrant/app
  become: yes
  become_user: vagrant

- name: Start App4
  shell: "nohup ruby /home/vagrant/app/app.rb > /var/log/app4.log 2>&1 &"
  args:
    chdir: /home/vagrant/app
  become: yes
  become_user: vagrant
