---
- name: Provision Target Nodes
  hosts: targets
  become: yes
  roles:
    - common
    - app_deploy

- name: Provision Control Node (Kali)
  hosts: scanners
  become: yes
  roles:
    - common
    - scanners
    - testing
